cloud:
  aws:
    region:
      static: us-east-1
    stack:
        auto: false
    credentials:
        access-key: AKIAUGDDBTJIQEAAGW4W
        secret-key: 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
logging:
  level:
    com:
      amazonans:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error